version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data from TPC-H dataset"
    config:
      tags: ['staging']
    columns:
      - name: customer_key
        description: "Primary key for customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer name"
        tests:
          - not_null
      - name: customer_address for 
        description: "Customer address"
      - name: nation_key
        description: "Foreign key to nation"
        tests:
          - not_null
      - name: customer_phone
        description: "Customer phone number"
      - name: account_balance
        description: "Customer account balance"
      - name: market_segment
        description: "Market segment"
      - name: customer_comment
        description: "Customer comment"

  - name: stg_orders
    description: "Cleaned order data from TPC-H dataset"
    config:
      tags: ['staging']
    columns:
      - name: order_key
        description: "Primary key for order"
        tests:
          - unique
          - not_null
      - name: customer_key
        description: "Foreign key to customer"
        tests:
          - not_null
      - name: order_status
        description: "Order status"
      - name: total_price
        description: "Total price of order"
      - name: order_date
        description: "Order date"
      - name: order_priority
        description: "Order priority"
      - name: clerk
        description: "Clerk who processed order"
      - name: ship_priority
        description: "Shipping priority"
      - name: order_comment
        description: "Order comment"

  - name: stg_lineitem
    description: "Cleaned line item data from TPC-H dataset"
    config:
      tags: ['staging']
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_key
            - line_number
    columns:
      - name: order_key
        description: "Foreign key to order and part of composite primary key"
        tests:
          - not_null
      - name: part_key
        description: "Foreign key to part"
        tests:
          - not_null
      - name: supplier_key
        description: "Foreign key to supplier"
        tests:
          - not_null
      - name: line_number
        description: "Line number in order"
      - name: quantity
        description: "Quantity ordered"
      - name: extended_price
        description: "Extended price"
      - name: discount
        description: "Discount applied"
      - name: tax
        description: "Tax applied"
      - name: return_flag
        description: "Return flag"
      - name: line_status
        description: "Line status"
      - name: ship_date
        description: "Ship date"
      - name: commit_date
        description: "Commit date"
      - name: receipt_date
        description: "Receipt date"
      - name: ship_instruct
        description: "Shipping instructions"
      - name: ship_mode
        description: "Shipping mode"
      - name: line_comment
        description: "Line item comment"

  - name: stg_supplier
    description: "Cleaned supplier data from TPC-H dataset"
    tags: ['staging']
    columns:
      - name: supplier_key
        description: "Primary key for supplier"
        tests:
          - unique
          - not_null
      - name: supplier_name
        description: "Supplier name"
        tests:
          - not_null
      - name: supplier_address
        description: "Supplier address"
      - name: nation_key
        description: "Foreign key to nation"
        tests:
          - not_null
      - name: supplier_phone
        description: "Supplier phone number"
      - name: account_balance
        description: "Supplier account balance"
      - name: supplier_comment
        description: "Supplier comment"

  - name: stg_nation
    description: "Cleaned nation data from TPC-H dataset"
    tags: ['staging']
    columns:
      - name: nation_key
        description: "Primary key for nation"
        tests:
          - unique
          - not_null
      - name: nation_name
        description: "Nation name"
        tests:
          - not_null
      - name: region_key
        description: "Foreign key to region"
        tests:
          - not_null
      - name: nation_comment
        description: "Nation comment"

  - name: stg_part
    description: "Cleaned part data from TPC-H dataset"
    tags: ['staging']
    columns:
      - name: part_key
        description: "Primary key for part"
        tests:
          - unique
          - not_null
      - name: part_name
        description: "Part name"
        tests:
          - not_null
      - name: manufacturer
        description: "Manufacturer"
      - name: brand
        description: "Brand"
      - name: part_type
        description: "Part type"
      - name: part_size
        description: "Part size"
      - name: container
        description: "Container type"
      - name: retail_price
        description: "Retail price"
      - name: part_comment
        description: "Part comment"

  - name: stg_partsupp
    description: "Cleaned part-supplier data from TPC-H dataset"
    tags: ['staging']
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - part_key
            - supplier_key
    columns:
      - name: part_key
        description: "Foreign key to part and part of composite primary key"
        tests:
          - not_null
      - name: supplier_key
        description: "Foreign key to supplier and part of composite primary key"
        tests:
          - not_null
      - name: available_quantity
        description: "Available quantity"
      - name: supply_cost
        description: "Supply cost"
      - name: partsupp_comment
        description: "Part-supplier comment"

  - name: stg_region
    description: "Cleaned region data from TPC-H dataset"
    tags: ['staging']
    columns:
      - name: region_key
        description: "Primary key for region"
        tests:
          - unique
          - not_null
      - name: region_name
        description: "Region name"
        tests:
          - not_null
      - name: region_comment
        description: "Region comment" 