version: 2

sources:
  - name: tpch
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    description: "TPC-H benchmark dataset for analytics"
    tables:
      - name: customer
        description: "Customer information table"
        columns:
          - name: c_custkey
            description: "Primary key for customer"
            tests:
              - unique
              - not_null
          - name: c_name
            description: "Customer name"
            tests:
              - not_null
          - name: c_address
            description: "Customer address"
          - name: c_nationkey
            description: "Foreign key to nation"
            tests:
              - not_null
          - name: c_phone
            description: "Customer phone number"
          - name: c_acctbal
            description: "Customer account balance"
          - name: c_mktsegment
            description: "Market segment"
          - name: c_comment
            description: "Customer comment"
      - name: orders
        description: "Order information table"
        columns:
          - name: o_orderkey
            description: "Primary key for order"
            tests:
              - unique
              - not_null
          - name: o_custkey
            description: "Foreign key to customer"
            tests:
              - not_null
          - name: o_orderstatus
            description: "Order status"
          - name: o_totalprice
            description: "Total price of order"
          - name: o_orderdate
            description: "Order date"
          - name: o_orderpriority
            description: "Order priority"
          - name: o_clerk
            description: "Clerk who processed order"
          - name: o_shippriority
            description: "Shipping priority"
          - name: o_comment
            description: "Order comment"
      - name: lineitem
        description: "Line item details table"
        columns:
          - name: l_orderkey
            description: "Foreign key to order"
            tests:
              - not_null
          - name: l_partkey
            description: "Foreign key to part"
            tests:
              - not_null
          - name: l_suppkey
            description: "Foreign key to supplier"
            tests:
              - not_null
          - name: l_linenumber
            description: "Line number in order"
          - name: l_quantity
            description: "Quantity ordered"
          - name: l_extendedprice
            description: "Extended price"
          - name: l_discount
            description: "Discount applied"
          - name: l_tax
            description: "Tax applied"
          - name: l_returnflag
            description: "Return flag"
          - name: l_linestatus
            description: "Line status"
          - name: l_shipdate
            description: "Ship date"
          - name: l_commitdate
            description: "Commit date"
          - name: l_receiptdate
            description: "Receipt date"
          - name: l_shipinstruct
            description: "Shipping instructions"
          - name: l_shipmode
            description: "Shipping mode"
          - name: l_comment
            description: "Line item comment"
      - name: supplier
        description: "Supplier information table"
        columns:
          - name: s_suppkey
            description: "Primary key for supplier"
            tests:
              - unique
              - not_null
          - name: s_name
            description: "Supplier name"
            tests:
              - not_null
          - name: s_address
            description: "Supplier address"
          - name: s_nationkey
            description: "Foreign key to nation"
            tests:
              - not_null
          - name: s_phone
            description: "Supplier phone number"
          - name: s_acctbal
            description: "Supplier account balance"
          - name: s_comment
            description: "Supplier comment"
      - name: nation
        description: "Nation information table"
        columns:
          - name: n_nationkey
            description: "Primary key for nation"
            tests:
              - unique
              - not_null
          - name: n_name
            description: "Nation name"
            tests:
              - not_null
          - name: n_regionkey
            description: "Foreign key to region"
            tests:
              - not_null
          - name: n_comment
            description: "Nation comment"
      - name: part
        description: "Part/product information table"
        columns:
          - name: p_partkey
            description: "Primary key for part"
            tests:
              - unique
              - not_null
          - name: p_name
            description: "Part name"
            tests:
              - not_null
          - name: p_mfgr
            description: "Manufacturer"
          - name: p_brand
            description: "Brand"
          - name: p_type
            description: "Part type"
          - name: p_size
            description: "Part size"
          - name: p_container
            description: "Container type"
          - name: p_retailprice
            description: "Retail price"
          - name: p_comment
            description: "Part comment"
      - name: partsupp
        description: "Part-supplier relationship table"
        columns:
          - name: ps_partkey
            description: "Foreign key to part"
            tests:
              - not_null
          - name: ps_suppkey
            description: "Foreign key to supplier"
            tests:
              - not_null
          - name: ps_availqty
            description: "Available quantity"
          - name: ps_supplycost
            description: "Supply cost"
          - name: ps_comment
            description: "Part-supplier comment"
      - name: region
        description: "Region information table"
        columns:
          - name: r_regionkey
            description: "Primary key for region"
            tests:
              - unique
              - not_null
          - name: r_name
            description: "Region name"
            tests:
              - not_null
          - name: r_comment
            description: "Region comment" 