name: Test Workflow Trigger

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'gotphoto_dbt_project/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Trigger
        run: |
          echo "✅ Workflow triggered successfully!"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Changed files:"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} 